### ISSUE TITLE
Boolean Data Type not enforced

### ISSUE THREAD

**Issue by amattu2** [jalik/js-form-parser#15]
When parsing a checkbox with the `data-type` property set to `boolean`, my expectation is that a parsed form will either result in a `true` or `false` value for that field; with true indicating a checked state, and false being unchecked. This is not the case.

e.g.

```HTML
<input name="abc" type="checkbox" data-type="boolean" value="true" checked>
```

```JavaScript
console.log(parseForm(form, { nullify: false }));
```

Outputs:
```JavaScript
{abc: null}
```
or
```JavaScript
{abc: true}
```
When the checkbox is **unchecked** vs. **checked**, respectively. Per the docs,

> Note: The boolean data-type will convert "1" and "true" to true, all other values are false.

We should be seeing either true or false, never null.

Is this expected functionality and is there a way to force an actual boolean result?

**Comment by jalik** [comment]
Hello @amattu2 , thank you for reporting this issue.
I can confirm that you should get a **boolean** when using `data-type="boolean"`.
I'll check and fix it in the next 24 hours (I am in the Pacific UTC-10).

**Comment by jalik** [comment]
@amattu2 please give a try to the v3, which should resolve your issue.

**Comment by jalik** [comment]
@amattu2 sorry I've released the v3 to fast, it contains some regressions.
I am currently improving the testing code and fixing bugs.
Hope to see a fix coming today or tomorrow.

**Comment by jalik** [comment]
@amattu2 `v3.1.0` released.

**Comment by amattu2** [comment]
Thanks for the prompt fix. I'll test it soon to confirm and report back.

**Comment by amattu2** [comment]
Sorry for the delay. Working as expected. Thanks!

**Comment by jalik** [comment]
@amattu2 thank you for taking the time to report the issue.
Have a nice day.
