### ISSUE TITLE
Failed to parse source map (missing)

### ISSUE THREAD

**Issue by amattu2** [jalik/js-form-parser#16]
After upgrading to `3.1.0` we're getting a missing source map warning when running our React app.

![image](https://github.com/jalik/js-form-parser/assets/38357871/781cd39b-cba8-4986-9601-4e3e724ac653)

It seems to be pulling from the correct CJS source.

![image](https://github.com/jalik/js-form-parser/assets/38357871/5852fe27-bbe1-4890-ac13-bb8d2a8bd3d0)

The parser works as expected, with the exception of this warning. Is this a package issue or an issue on our end?

**Comment by jalik** [comment]
Hello @amattu2, I don't have this warning on compilation with Webpack@5 and the 3.1.0 version of the lib.
I see that the path is referring to `/form-parser/src/index.ts`, but the `src` directory is not published (at least not in this version, maybe it was previously by error).

Make sure to replace your imports containing `form-parser/src/` with `form-parser/esm/`.

**Comment by amattu2** [comment]
I can't replicate it with a new React app, it must be something with our configuration. Closing this, but I'll update if I find a solution (for any future readers).

Thanks again @jalik
